title: An introduction to small bore airgun hunting in Africa
author: Eng-Masunda
email: iengineerwebsites@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The following discussion introduces the subject of hunting with with small bore (.177 & .22 calibre) airguns for legal and ethical conservation efforts in Africa. The discussion 
  focuses on the different ammunition and technologies that are currently on the market and strives to measure their efficacy in humanely dispatching small game. The discussion also 
  highlights all the available game that can be humanley dispatched by airguns of varying power and accuracy.
theme: minima
# social links
twitter_username: iengineerWebSo1# DO NOT include the @ character, or else the build will fail!
github_username:  Eng-Masunda # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
